---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: making/alpine-java-bash-git
inputs:
  - name: uaa-repo
  - name: uaa-repo-staging
  - name: uaa-ci
outputs:
  - name: master-out
run:
  path: /bin/bash
  args:
  - repo-release/ci/tasks/merge-release-to-master.sh