platform: linux
image_resource:
  type: docker-image
  source:
    repository: making/alpine-java-bash-git
inputs:
  - name: repo-version
  - name: repo-staging
  - name: repo-prod
  - name: repo-ci
  - name: m2
outputs:
  - name: release-out
run:
  path: bash
  args:
    - repo-ci/ci/tasks/bump-to-next-develop-version.sh
