---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: making/alpine-java-bash-git
inputs:
  - name: uaa-repo-other
  - name: uaa-repo-staging
  - name: uaa-ci
outputs:
  - name: other-out
run:
  path: bash
  args:
  - uaa-ci/ci/tasks/merge-release-to-other.sh