platform: linux
image_resource:
  type: docker-image
  source:
    repository: making/alpine-java-bash-git
inputs:
  - name: uaa-version
  - name: uaa-repo
  - name: uaa-ci
  - name: m2
outputs:
  - name: master-out
run:
  path: bash
  args:
    - repo-release/ci/tasks/bump-to-release-version.sh