---
resources:
  - name: uaa-repo
    type: git
    source:
      uri: https://github.com/maki-home/uaa.git
      branch: master
  - name: cf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true
  - name: m2
    type: docker-image
    source:
      repository: making/home-m2
  - name: dockerhub
    type: docker-image
    source:
      repository: making/maki-uaa
      username: {{docker-username}}
      password: {{docker-password}}
      email: {{docker-email}}
jobs:
  - name: uaa-unit
    plan:
      - get: uaa-repo
        trigger: true
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine
          inputs:
            - name: uaa-repo
              path: repo
            - name: m2
          run:
            path: sh
            args:
            - repo/ci/tasks/unit.sh
          params:
            _JAVA_OPTIONS: -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP -Djava.security.egd=file:/dev/./urandom
  - name: uaa-deploy
    plan:
      - get: uaa-repo
        trigger: true
        passed: [ uaa-unit ]
      - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine
          inputs:
            - name: uaa-repo
              path: repo
            - name: m2
          outputs:
            - name: output
          run:
            path: sh
            args:
            - repo/ci/tasks/package.sh
      - put: cf
        params:
          manifest: uaa-repo/manifest-pez.yml
          path: output/app.jar
          current_app_name: home-uaa
  - name: uaa-docker-push
    plan:
      - get: uaa-repo
        trigger: true
        passed: [ uaa-unit ]
      - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine
          inputs:
            - name: uaa-repo
              path: repo
            - name: m2
          outputs:
            - name: output
          run:
            path: sh
            args:
            - repo/ci/tasks/package.sh
      - put: dockerhub
        params:
          build: .
          dockerfile: uaa-repo/Dockerfile
          tag_as_latest: true
