---
resources:
  - name: uaa-repo-prod
    type: git
    source:
      uri: git@github.com:maki-home/uaa.git
      branch: master
      private_key: {{github-private-key}}
  - name: uaa-repo-staging
    type: git
    source:
      uri: git@github.com:maki-home/uaa.git
      branch: release
      private_key: {{github-private-key}}
  - name: uaa-repo-dev
    type: git
    source:
      uri: git@github.com:maki-home/uaa.git
      branch: develop
      private_key: {{github-private-key}}
  - name: uaa-ci
    type: git
    source:
      uri: git@github.com:maki-home/uaa.git
      branch: develop
      private_key: {{github-private-key}}
  - name: uaa-version
    type: semver
    source:
      uri: git@github.com:maki-home/uaa-version.git
      branch: master
      private_key: {{github-private-key}}
      file: version
      driver: git
      initial_version: 0.5.0
  - name: utils
    type: git
    source:
      uri: https://github.com/maki-home/concourse-utils
      branch: master
  - name: cf-prod
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: home
      skip_cert_check: true
  - name: cf-staging
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: home-staging
      skip_cert_check: true
  - name: cf-dev
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: home-dev
      skip_cert_check: true
  - name: m2
    type: docker-image
    source:
      repository: making/home-m2
  - name: dockerhub
    type: docker-image
    source:
      repository: making/maki-uaa-server
      username: {{docker-username}}
      password: {{docker-password}}
      email: {{docker-email}}
jobs:
  ############# Dev #############
  - name: uaa-unit-test-dev
    plan:
      - aggregate:
        - get: uaa-repo
          resource: uaa-repo-dev
          trigger: true
        - get: uaa-ci
        - get: utils
        - get: m2
      - task: unit
        file: uaa-ci/ci/tasks/uaa-unit-test.yml
  - name: uaa-deploy-to-nexus-dev
    plan:
      - aggregate:
        - get: uaa-repo
          resource: uaa-repo-dev
          trigger: true
          passed:
          - uaa-unit-test-dev
        - get: uaa-ci
        - get: utils
        - get: m2
      - task: deploy
        file: uaa-ci/ci/tasks/uaa-deploy-to-nexus.yml
        params:
          NEXUS_USERNAME: {{nexus-username}}
          NEXUS_PASSWORD: {{nexus-password}}
  - name: uaa-deploy-to-cf-dev
    plan:
      - aggregate:
        - get: uaa-repo
          resource: uaa-repo-dev
          trigger: true
          passed:
          - uaa-deploy-to-nexus-dev
        - get: uaa-version
        - get: uaa-ci
        - get: utils
      - task: download
        file: uaa-ci/ci/tasks/uaa-download-snapshot.yml
      - put: cf-dev
        params:
          manifest: uaa-repo/uaa-server/manifest-pez-dev.yml
          path: output/app.jar
          current_app_name: home-uaa-dev
  ############# Staging #############
  - name: uaa-unit-test-staging
    plan:
      - aggregate:
        - get: uaa-repo
          resource: uaa-repo-staging
          trigger: true
        - get: uaa-ci
        - get: utils
        - get: m2
      - task: unit
        file: uaa-ci/ci/tasks/uaa-unit-test.yml
  - name: uaa-deploy-to-nexus-staging
    plan:
      - aggregate:
        - get: uaa-repo
          resource: uaa-repo-staging
          trigger: true
          passed:
          - uaa-unit-test-staging
        - get: uaa-ci
        - get: utils
        - get: m2
      - task: deploy
        file: uaa-ci/ci/tasks/uaa-deploy-to-nexus.yml
        params:
          NEXUS_USERNAME: {{nexus-username}}
          NEXUS_PASSWORD: {{nexus-password}}
  - name: uaa-deploy-to-cf-staging
    plan:
      - aggregate:
        - get: uaa-repo
          resource: uaa-repo-staging
          trigger: true
          passed:
          - uaa-deploy-to-nexus-staging
        - get: uaa-version
        - get: uaa-ci
        - get: utils
      - task: download
        file: uaa-ci/ci/tasks/uaa-download-snapshot.yml
      - put: cf-staging
        params:
          manifest: uaa-repo/uaa-server/manifest-pez-staging.yml
          path: output/app.jar
          current_app_name: home-uaa-staging
  ############# Prod #############
  - name: merge-release-to-master
    public: true
    plan:
      - aggregate:
        - get: uaa-repo
          resource: uaa-repo-prod
        - get: uaa-repo-staging
          passed:
          - uaa-deploy-to-cf-staging
        - get: uaa-ci
      - task: merge-release-to-master
        file: uaa-ci/ci/tasks/uaa-merge-release-to-master.yml
        params:
          GIT_EMAIL: {{git-email}}
          GIT_NAME: {{git-name}}
      - put: uaa-repo-prod
        params:
          repository: master-out
  - name: uaa-unit-test-prod
    plan:
      - aggregate:
        - get: uaa-repo
          resource: uaa-repo-prod
          trigger: true
          passed:
          - merge-release-to-master
        - get: uaa-ci
        - get: utils
        - get: m2
      - task: unit
        file: uaa-ci/ci/tasks/uaa-unit-test.yml
  - name: tag-master
    public: true
    plan:
      - aggregate:
        - get: uaa-repo
          resource: uaa-repo-prod
          passed: [ uaa-unit-test-prod ]
          trigger: true
        - get: uaa-ci
        - get: uaa-version
        - get: utils
        - get: m2
      - task: bump-to-release-version
        file: uaa-ci/ci/tasks/uaa-bump-to-release-version.yml
        params:
          GIT_EMAIL: {{git-email}}
          GIT_NAME: {{git-name}}
      - put: uaa-repo-prod
        params:
          repository: master-out
          tag: uaa-version/number
  - name: uaa-deploy-to-nexus-prod
    plan:
      - aggregate:
        - get: uaa-repo
          resource: uaa-repo-prod
          trigger: true
          passed:
          - tag-master
        - get: uaa-ci
        - get: utils
        - get: m2
      - task: deploy
        file: uaa-ci/ci/tasks/uaa-deploy-to-nexus.yml
        params:
          NEXUS_USERNAME: {{nexus-username}}
          NEXUS_PASSWORD: {{nexus-password}}
  - name: uaa-deploy-to-cf-prod
    plan:
      - aggregate:
        - get: uaa-repo
          resource: uaa-repo-prod
          trigger: true
          passed:
          - uaa-deploy-to-nexus-prod
        - get: uaa-version
        - get: uaa-ci
        - get: utils
      - task: download
        file: uaa-ci/ci/tasks/uaa-download-release.yml
      - put: cf-prod
        params:
          manifest: uaa-repo/uaa-server/manifest-pez.yml
          path: output/app.jar
          current_app_name: home-uaa
  - name: uaa-deploy-to-dockerhub-prod
    plan:
      - aggregate:
        - get: uaa-repo
          resource: uaa-repo-prod
          trigger: true
          passed:
          - uaa-deploy-to-nexus-prod
        - get: uaa-version
        - get: uaa-ci
        - get: utils
      - task: download
        file: uaa-ci/ci/tasks/uaa-download-release.yml
      - put: dockerhub
        params:
          build: .
          dockerfile: uaa-repo/uaa-server/Dockerfile
          tag_as_latest: true
          tag: uaa-version/number
  - name: bump-to-next-minor-version
    plan:
      - aggregate:
        - get: uaa-repo
          resource: uaa-repo-dev
        - get: uaa-repo-prod
          passed:
          - uaa-deploy-to-cf-prod
          - uaa-deploy-to-dockerhub-prod
          trigger: true
        - get: uaa-version
          params:
            bump: minor
        - get: uaa-ci
        - get: m2
      - task: bump-to-next-minor-version
        file: uaa-ci/ci/tasks/uaa-bump-to-next-develop-version.yml
        params:
          GIT_EMAIL: {{git-email}}
          GIT_NAME: {{git-name}}
      - put: uaa-repo-dev
        resource: uaa-repo-dev
        params:
          repository: develop-out
      - put: uaa-version
        params:
          file: uaa-version/number
  - name: bump-to-next-patch-version
    plan:
      - aggregate:
        - get: uaa-repo
          resource: uaa-repo-dev
        - get: uaa-repo-prod
          passed:
          - tag-master
        - get: uaa-version
          params:
            bump: patch
        - get: uaa-ci
        - get: m2
      - task: bump-to-next-develop-version
        file: uaa-ci/ci/tasks/uaa-bump-to-next-develop-version.yml
        params:
          GIT_EMAIL: {{git-email}}
          GIT_NAME: {{git-name}}
      - put: uaa-repo-dev
        resource: uaa-repo-dev
        params:
          repository: develop-out
      - put: uaa-version
        params:
          file: uaa-version/number