---
resources:
  - name: uaa-repo
    type: git
    source:
      uri: https://github.com/maki-home/uaa.git
      branch: master
  - name: utils
    type: git
    source:
      uri: https://github.com/maki-home/concourse-utils
      branch: master
  - name: cf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true
  - name: m2
    type: docker-image
    source:
      repository: making/home-m2
  - name: dockerhub
    type: docker-image
    source:
      repository: making/maki-uaa-server
      username: {{docker-username}}
      password: {{docker-password}}
      email: {{docker-email}}
jobs:
  - name: uaa-unit
    plan:
      - aggregate:
        - get: uaa-repo
          trigger: true
        - get: utils
        - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: making/alpine-java-bash-git
          inputs:
            - name: uaa-repo
            - name: utils
            - name: m2
          run:
            path: sh
            args:
            - -c
            - |
              BASEDIR=`pwd`
              cd uaa-repo/uaa-server
              $BASEDIR/utils/scripts/add-repos-in-pom-xml.sh
              cd -
              uaa-repo/ci/tasks/unit.sh uaa-repo/uaa-server
          params:
            _JAVA_OPTIONS: -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP -Djava.security.egd=file:/dev/./urandom
  - name: uaa-deploy
    plan:
      - aggregate:
        - get: uaa-repo
          trigger: true
          passed: [ uaa-unit ]
        - get: utils
        - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: making/alpine-java-bash-git
          inputs:
            - name: uaa-repo
            - name: utils
            - name: m2
          outputs:
            - name: output
          run:
            path: sh
            args:
            - -c
            - |
              BASEDIR=`pwd`
              cd uaa-repo/uaa-server
              $BASEDIR/utils/scripts/add-repos-in-pom-xml.sh
              cd -
              uaa-repo/ci/tasks/package.sh uaa-repo/uaa-server
      - put: cf
        params:
          manifest: uaa-repo/uaa-server/manifest-pez.yml
          path: output/app.jar
          current_app_name: home-uaa
  - name: uaa-docker-push
    plan:
      - aggregate:
        - get: uaa-repo
          trigger: true
          passed: [ uaa-unit ]
        - get: m2
        - get: utils
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: making/alpine-java-bash-git
          inputs:
            - name: uaa-repo
            - name: utils
            - name: m2
          outputs:
            - name: output
          run:
            path: sh
            args:
            - -c
            - |
              BASEDIR=`pwd`
              cd uaa-repo/uaa-server
              $BASEDIR/utils/scripts/add-repos-in-pom-xml.sh
              cd -
              uaa-repo/ci/tasks/package.sh uaa-repo/uaa-server
      - put: dockerhub
        params:
          build: .
          dockerfile: uaa-repo/uaa-server/Dockerfile
          tag_as_latest: true
